import type { Transaction } from '@/types';

export const mockTransactions: Transaction[] = [
  {
    id: 'txn-001',
    date: '2024-01-15',
    description: 'Global Tech Corp - Salary',
    amount: 8450.0,
    category: 'Salary',
    type: 'income',
    paymentMethod: 'Deposit',
  },
  {
    id: 'txn-002',
    date: '2024-01-14',
    description: 'Whole Foods Market',
    amount: 184.2,
    category: 'Food & Dining',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-003',
    date: '2024-01-13',
    description: 'Apple Subscription',
    amount: 14.99,
    category: 'Entertainment',
    type: 'expense',
    paymentMethod: 'Recurring',
  },
  {
    id: 'txn-004',
    date: '2024-01-12',
    description: 'Freelance Design Project',
    amount: 2200.0,
    category: 'Freelance',
    type: 'income',
    paymentMethod: 'ACH Transfer',
  },
  {
    id: 'txn-005',
    date: '2024-01-11',
    description: 'Equinox Membership',
    amount: 265.0,
    category: 'Healthcare',
    type: 'expense',
    paymentMethod: 'Direct Debit',
  },
  {
    id: 'txn-006',
    date: '2024-01-10',
    description: 'Uber Ride',
    amount: 24.5,
    category: 'Transport',
    type: 'expense',
    paymentMethod: 'App',
  },
  {
    id: 'txn-007',
    date: '2024-01-09',
    description: 'Amazon.com Purchase',
    amount: 112.9,
    category: 'Shopping',
    type: 'expense',
    paymentMethod: 'Online',
  },
  {
    id: 'txn-008',
    date: '2024-01-08',
    description: 'Utility Bill - Power',
    amount: 89.0,
    category: 'Utilities',
    type: 'expense',
    paymentMethod: 'Wire',
  },
  {
    id: 'txn-009',
    date: '2024-01-07',
    description: 'Starbucks Coffee',
    amount: 6.45,
    category: 'Food & Dining',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-010',
    date: '2024-01-06',
    description: 'Monthly Rent Payment',
    amount: 2400.0,
    category: 'Housing',
    type: 'expense',
    paymentMethod: 'Wire',
  },
  {
    id: 'txn-011',
    date: '2024-01-05',
    description: 'Project Dividend Payment',
    amount: 8400.0,
    category: 'Freelance',
    type: 'income',
    paymentMethod: 'ACH Transfer',
  },
  {
    id: 'txn-012',
    date: '2024-01-04',
    description: 'Monthly Mortgage',
    amount: 3150.0,
    category: 'Housing',
    type: 'expense',
    paymentMethod: 'Direct Debit',
  },
  {
    id: 'txn-013',
    date: '2024-01-03',
    description: 'Apple Store - New York',
    amount: 1299.0,
    category: 'Technology',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-014',
    date: '2024-01-02',
    description: 'Lufthansa Airlines',
    amount: 842.2,
    category: 'Travel',
    type: 'expense',
    paymentMethod: 'Online',
  },
  {
    id: 'txn-015',
    date: '2024-01-01',
    description: 'Eleven Madison Park',
    amount: 345.0,
    category: 'Food & Dining',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-016',
    date: '2023-12-28',
    description: 'Netflix Subscription',
    amount: 15.99,
    category: 'Entertainment',
    type: 'expense',
    paymentMethod: 'Recurring',
  },
  {
    id: 'txn-017',
    date: '2023-12-27',
    description: 'Tesla Supercharge',
    amount: 45.2,
    category: 'Transport',
    type: 'expense',
    paymentMethod: 'App',
  },
  {
    id: 'txn-018',
    date: '2023-12-25',
    description: 'Delta Airlines',
    amount: 842.15,
    category: 'Travel',
    type: 'expense',
    paymentMethod: 'Online',
  },
  {
    id: 'txn-019',
    date: '2023-12-22',
    description: 'Year-End Bonus',
    amount: 5000.0,
    category: 'Salary',
    type: 'income',
    paymentMethod: 'Deposit',
  },
  {
    id: 'txn-020',
    date: '2023-12-20',
    description: 'Costco Wholesale',
    amount: 312.45,
    category: 'Shopping',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-021',
    date: '2023-12-18',
    description: 'Water Bill',
    amount: 54.0,
    category: 'Utilities',
    type: 'expense',
    paymentMethod: 'Direct Debit',
  },
  {
    id: 'txn-022',
    date: '2023-12-15',
    description: 'Global Tech Corp - Salary',
    amount: 8450.0,
    category: 'Salary',
    type: 'income',
    paymentMethod: 'Deposit',
  },
  {
    id: 'txn-023',
    date: '2023-12-13',
    description: 'Trader Joes',
    amount: 78.3,
    category: 'Food & Dining',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-024',
    date: '2023-12-10',
    description: 'Gym Membership',
    amount: 49.99,
    category: 'Healthcare',
    type: 'expense',
    paymentMethod: 'Recurring',
  },
  {
    id: 'txn-025',
    date: '2023-12-08',
    description: 'Consulting Invoice',
    amount: 3500.0,
    category: 'Freelance',
    type: 'income',
    paymentMethod: 'ACH Transfer',
  },
  {
    id: 'txn-026',
    date: '2023-12-05',
    description: 'Internet Bill',
    amount: 79.99,
    category: 'Utilities',
    type: 'expense',
    paymentMethod: 'Recurring',
  },
  {
    id: 'txn-027',
    date: '2023-12-03',
    description: 'Lyft Ride',
    amount: 18.75,
    category: 'Transport',
    type: 'expense',
    paymentMethod: 'App',
  },
  {
    id: 'txn-028',
    date: '2023-12-01',
    description: 'Monthly Rent Payment',
    amount: 2400.0,
    category: 'Housing',
    type: 'expense',
    paymentMethod: 'Wire',
  },
  {
    id: 'txn-029',
    date: '2023-11-28',
    description: 'Spotify Premium',
    amount: 9.99,
    category: 'Entertainment',
    type: 'expense',
    paymentMethod: 'Recurring',
  },
  {
    id: 'txn-030',
    date: '2023-11-25',
    description: 'Ikea Purchase',
    amount: 456.0,
    category: 'Shopping',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-031',
    date: '2023-11-22',
    description: 'Chipotle Mexican Grill',
    amount: 15.2,
    category: 'Food & Dining',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-032',
    date: '2023-11-20',
    description: 'United Airlines',
    amount: 534.0,
    category: 'Travel',
    type: 'expense',
    paymentMethod: 'Online',
  },
  {
    id: 'txn-033',
    date: '2023-11-18',
    description: 'Dental Checkup',
    amount: 175.0,
    category: 'Healthcare',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-034',
    date: '2023-11-15',
    description: 'Global Tech Corp - Salary',
    amount: 8450.0,
    category: 'Salary',
    type: 'income',
    paymentMethod: 'Deposit',
  },
  {
    id: 'txn-035',
    date: '2023-11-12',
    description: 'Gas Station',
    amount: 62.0,
    category: 'Transport',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-036',
    date: '2023-11-10',
    description: 'Phone Bill',
    amount: 85.0,
    category: 'Utilities',
    type: 'expense',
    paymentMethod: 'Recurring',
  },
  {
    id: 'txn-037',
    date: '2023-11-08',
    description: 'Freelance Web Dev',
    amount: 4200.0,
    category: 'Freelance',
    type: 'income',
    paymentMethod: 'ACH Transfer',
  },
  {
    id: 'txn-038',
    date: '2023-11-05',
    description: 'Target Shopping',
    amount: 134.67,
    category: 'Shopping',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-039',
    date: '2023-11-03',
    description: 'Electric Bill',
    amount: 112.0,
    category: 'Utilities',
    type: 'expense',
    paymentMethod: 'Direct Debit',
  },
  {
    id: 'txn-040',
    date: '2023-11-01',
    description: 'Monthly Rent Payment',
    amount: 2400.0,
    category: 'Housing',
    type: 'expense',
    paymentMethod: 'Wire',
  },
  {
    id: 'txn-041',
    date: '2023-10-28',
    description: 'Sushi Nakazawa',
    amount: 220.0,
    category: 'Food & Dining',
    type: 'expense',
    paymentMethod: 'Card',
  },
  {
    id: 'txn-042',
    date: '2023-10-15',
    description: 'Global Tech Corp - Salary',
    amount: 8450.0,
    category: 'Salary',
    type: 'income',
    paymentMethod: 'Deposit',
  },
];
